export function getLitActionModuleFileContent({
  ipfsCid,
  content,
}: {
  ipfsCid: string;
  content: string;
}) {
  return `/**
* DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
* @type {string}
*/
const code = ${JSON.stringify(content)};
module.exports = {
  "code": code,
  "ipfsCid": "${ipfsCid}",
};
`;
}

export function getMetadataJsonFileContent({ ipfsCid }: { ipfsCid: string }) {
  return `{
  "ipfsCid": "${ipfsCid}"
}
`;
}
