packages:
  - 'packages/libs/*'
  - 'packages/apps/*'
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - 'bufferutil'
  - 'bun'
  - 'core-js'
  - 'esbuild'
  - 'fsevents'
  - 'keccak'
  - 'nx'
  - 'protobufjs'
  - 'unrs-resolver'
  - 'utf-8-validate'
overrides:
  typescript: '5.8.3'
