packages:
  - packages/registry-backend
  - packages/mcp
  - packages/sdk
  - packages/vincent-rest-api
  - packages/app-dashboard
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - bun
  - core-js
  - esbuild
  - fsevents
  - keccak
  - nx
  - protobufjs
  - unrs-resolver
  - utf-8-validate
