import { EXAMPLE_WALLET_ADDRESS } from '../constants';
import { rawTransactionSchema } from './installedApp';
import { z } from './openApiZod';

export const uninstallAppRequest = z
  .object({
    appVersion: z.number().int().positive().openapi({
      description: 'The version of the app to uninstall',
      example: 1,
    }),
    userControllerAddress: z
      .string()
      .regex(/^0x[a-fA-F0-9]{40}$/)
      .openapi({
        description: 'EOA address that controls the user smart wallet',
        example: EXAMPLE_WALLET_ADDRESS,
      }),
    sponsorGas: z.boolean().optional().openapi({
      description:
        'If true (default), returns EIP2771 typed data for sponsored gas relay. If false, returns raw transaction data for direct EOA submission (user pays gas).',
      example: true,
    }),
  })
  .strict();

export const uninstallAppResponse = z
  .object({
    rawTransaction: rawTransactionSchema.optional().openapi({
      description: 'Raw transaction data for direct EOA submission. Present when sponsorGas=false.',
    }),
    uninstallDataToSign: z.object({}).passthrough().optional().openapi({
      description:
        'The EIP2771 TypedData to sign for sponsored gas relay. Present when sponsorGas=true (default).',
    }),
  })
  .strict();

export const completeUninstallRequest = z
  .object({
    typedDataSignature: z.string().openapi({
      description: 'The signature of the typed data from the user wallet',
      example: '0x...',
    }),
    uninstallDataToSign: z.object({}).passthrough().openapi({
      description:
        'The uninstallDataToSign object returned from uninstall-app. Generated by the Gelato SDK.',
    }),
  })
  .strict();

export const completeUninstallResponse = z
  .object({
    transactionHash: z.string().openapi({
      description: 'The transaction hash of the completed uninstall transaction',
      example: '0x9d260d1bbe075be0cda52a3271df062748f3182ede91b3aae5cd115f7b26552b',
    }),
  })
  .strict();
