// src/bundler/plugins/bundledTool.ts

import { Plugin } from 'rollup';
import path from 'path';
import fs from 'fs';

export function bundledTool({
  outputFilePath,
  sourceToolFilePath,
}: {
  outputFilePath: string;
  sourceToolFilePath: string;
}): Plugin {
  const relativeToolPath = path.resolve(path.dirname(outputFilePath), sourceToolFilePath);

  return {
    name: 'bundled-tool-generator',
    async generateBundle() {
      const bundledPath = path.join(path.dirname(outputFilePath), 'vincent-bundled-tool.ts');
      const code = `/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 */

import { asBundledVincentTool } from '@lit-protocol/vincent-tool-sdk';
import { vincentTool } from '${relativeToolPath}';
import metadata from './vincent-tool-metadata.json';

if(!metadata.ipfsCid) {
  throw new Error('ipfsCid is not defined in metadata JSON file');
}

export const bundledVincentTool = asBundledVincentTool(vincentTool, metadata.ipfsCid);
`;
      fs.writeFileSync(bundledPath, code);
    },
  };
}
