const fs = require('fs');
const path = require('path');

const esbuild = require('esbuild');
const { polyfillNode } = require('esbuild-plugin-polyfill-node');
const Hash = require('ipfs-only-hash');

function aliasFetch() {
  const shim = path.resolve(__dirname, 'deno-fetch-shim.js');

  return {
    name: 'alias-fetch',
    setup(build) {
      // node-fetch root
      build.onResolve({ filter: /^node-fetch$/ }, () => ({ path: shim }));

      // any cross-fetch entry: "cross-fetch", "cross-fetch/…"
      build.onResolve({ filter: /^cross-fetch(\/.*)?$/ }, () => ({ path: shim }));
    },
  };
}

const ensureDirectoryExistence = (filePath) => {
  const dirname = path.dirname(filePath);
  console.log('dirname', dirname);
  if (!fs.existsSync(dirname)) {
    fs.mkdirSync(dirname, { recursive: true });
  }
};

function litActionHandlerCode() {
  return `/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 */
 
import { vincentPolicyHandler } from '@lit-protocol/vincent-tool-sdk';

import { vincentPolicy } from '../lib/vincent-policy';
import { toolParamsSchema } from '../lib/schemas';

declare const context: {
  toolIpfsCid: string;
  delegatorPkpEthAddress: string;
};

declare const toolParams: typeof toolParamsSchema;

(async () => {
  return await vincentPolicyHandler({
    vincentPolicy: vincentPolicy,
    context,
    toolParams,
  });
})();`;
}

function getBundledVincentPolicyCode() {
  return `/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 */
 
import { asBundledVincentPolicy } from '@lit-protocol/vincent-tool-sdk';
import { vincentPolicy } from '../lib/vincent-policy';
import metadata from './vincent-policy-metadata.json';

if(!metadata.ipfsCid) {
  throw new Error('ipfsCid is not defined in metadata JSON file');
}

export const bundledVincentPolicy = asBundledVincentPolicy(vincentPolicy, { ipfsCid: metadata.ipfsCid, packageName: "${process.env.PNPM_PACKAGE_NAME}" as const });
`;
}

function litActionModuleCode({ ipfsCid, content }) {
  return `/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 * @type {string}
 */
const code = ${JSON.stringify(content)};
module.exports = {
  "code": code,
  "ipfsCid": "${ipfsCid}",
};
`;
}

function metadataJsonFile({ ipfsCid }) {
  return `{
  "ipfsCid": "${ipfsCid}"
}
`;
}

const createPolicyHandlerFile = {
  name: 'create-vincent-policy-handler-ts-file',
  setup(build) {
    build.initialOptions.write = false;

    build.onEnd(async (result) => {
      console.log('create-vincent-policy-handler-ts-file');

      if (result.errors.length > 0) {
        console.error('Build failed with errors:', result.errors);
        return;
      }

      const outputFile = result.outputFiles[0];
      const wrappedContent = litActionHandlerCode();
      const outputPath = path.dirname(path.resolve(outputFile.path));
      console.log('outputPath', outputPath);
      ensureDirectoryExistence(path.resolve(outputFile.path));

      const wrappedFilePath = path.join(outputPath, 'vincent-policy-handler.ts');

      // Write the modified content back to the output file
      console.log('writing file', { wrappedFilePath });
      fs.writeFileSync(wrappedFilePath, wrappedContent);
    });
  },
};

const createBundledPolicyFile = {
  name: 'create-vincent-bundled-policy-file',
  setup(build) {
    // Ensure write is set to false so our plugin will always receive outputFiles
    build.initialOptions.write = false;

    const sourceDir = path.dirname(build.initialOptions.entryPoints[0]);

    console.log(sourceDir);
    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        console.error('Build failed with errors:', result.errors);
        return;
      }
      const outputFile = result.outputFiles[0];

      const vincentPolicyPath = path.join(sourceDir, '../generated/vincent-bundled-policy.ts');
      const content = outputFile.text;
      const ipfsCid = await Hash.of(content);

      const bundledVincentPolicyCode = getBundledVincentPolicyCode();
      fs.writeFileSync(vincentPolicyPath, bundledVincentPolicyCode);

      const outputPath = path.dirname(path.resolve(outputFile.path));
      const vincentPolicyMetadataPath = path.join(outputPath, 'vincent-policy-metadata.json');
      const metadataJsonContent = metadataJsonFile({ ipfsCid });
      fs.writeFileSync(vincentPolicyMetadataPath, metadataJsonContent);
    });
  },
};

const wrapIIFEInStringPlugin = {
  name: 'wrap-iife-in-string',
  setup(build) {
    // Ensure write is set to false so our plugin will always receive outputFiles
    build.initialOptions.write = false;

    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        console.error('Build failed with errors:', result.errors);
        return;
      }

      const outputFile = result.outputFiles[0];
      const content = outputFile.text;
      const ipfsCid = await Hash.of(content);
      const wrappedContent = litActionModuleCode({ content, ipfsCid });
      const outputPath = path.resolve(outputFile.path);
      ensureDirectoryExistence(outputPath);

      // Write the modified content back to the output file
      fs.writeFileSync(outputPath.replace('.js', '.bundled.js'), wrappedContent);
    });
  },
};

(async () => {
  // Stage 1: First we write the vincent-policy-handler.ts file that contains our `vincentPolicyHandler()` wrapper code
  await esbuild.build({
    tsconfig: './tsconfig.lib.json',
    entryPoints: ['./src/lib/vincent-policy.ts'],
    bundle: true,
    minify: false,
    sourcemap: false,
    treeShaking: true,
    metafile: true,
    outdir: './src/generated/',
    // external: ['ethers'],
    plugins: [createPolicyHandlerFile],
    platform: 'browser',
  });

  // Stage 2:
  // - Create the `asBundledVincentPolicy` file with computed packageName
  // - Bundle `vincent-policy-handler.ts` as the LIT action executable code to be deployed to IPFS
  try {
    await esbuild
      .build({
        tsconfig: './tsconfig.lib.json',
        entryPoints: ['./src/generated/vincent-policy-handler.ts'],
        bundle: true,
        minify: false,
        sourcemap: false,
        treeShaking: true,
        metafile: true,
        outdir: './src/generated/',
        // external: ['ethers'],
        plugins: [
          aliasFetch(),
          polyfillNode({
            globals: {
              Buffer: true,
              process: true,
            },
            modules: {
              crypto: true,
              http: true,
              https: true,
              stream: true,
              zlib: true,
              url: true,
              util: true,
            },
          }),
          wrapIIFEInStringPlugin,
          createBundledPolicyFile,
        ],
        platform: 'browser',
      })
      .then((result) => {
        result.outputFiles.forEach((file) => {
          const bytes = file.text.length;
          const mbInBinary = (bytes / (1024 * 1024)).toFixed(4);
          const mbInDecimal = (bytes / 1_000_000).toFixed(4);

          console.log(
            `✅ ${file.path
              .split('/')
              .pop()}\n- ${mbInDecimal} MB (in decimal)\n- ${mbInBinary} MB (in binary)`,
          );
        });
      });
    console.log('✅ Lit actions built successfully');
  } catch (e) {
    console.error('❌ Error building lit actions: ', e);
    process.exit(1);
  }
})();
